### PR TITLE
Fix unsafe ranges

### LINKED ISSUE #16: Mark `get_lang_from_parts` as unsafe
Quoting Manish:

"Typically you still mark things as unsafe internally up to the point where you can ensure the invariants are upheld

Put another way, every use of `unsafe` could/should have a comment explaining why the invariants are being upheld. If you don't have a way to do that (e.g. here, where the invariants are being upheld elsewhere) you probably need to expand the usage"

_Originally posted by @Manishearth in https://github.com/zbraniecki/unic-locale/pull/15_

### PR DESCRIPTION
**Pull request by zbraniecki**
Fixes #16.

### CODE REVIEW

File: unic-langid-impl/src/likelysubtags/mod.rs [hunk 1]
```diff
@@ -33,7 +33,7 @@ pub fn add_likely_subtags(
                 })
                 .ok();
             if let Some(r) = result {
-                return get_lang_from_parts(tables::LANG_REGION[r].2, None, None, None);
+                return unsafe { get_lang_from_parts(tables::LANG_REGION[r].2, None, None, None) };
             }
```
Comment (Manishearth) [inline unic-langid-impl/src/likelysubtags/mod.rs]: ideally leave a comment on each use of unsafe explaining why it's actually safe to do (in these cases, probably something like "safe because all table entries are well formed")
